import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import axios from 'axios';
import { ArrowLeft, User, Activity, FileText, AlertTriangle } from 'lucide-react';

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000/api";

export const PatientDetailsPage = () => {
    const { id } = useParams();

    const { data: patientData, isLoading: patientLoading } = useQuery({
        queryKey: ['doctor', 'patient', id],
        queryFn: async () => {
            const response = await axios.get(`${API_URL}/doctor/patients/${id}`);
            return response.data;
        }
    });

    const { data: reports, isLoading: reportsLoading } = useQuery({
        queryKey: ['doctor', 'patient', id, 'reports'],
        queryFn: async () => {
            const response = await axios.get(`${API_URL}/ai-reports/patient/${id}`);
            return response.data;
        }
    });

    if (patientLoading) {
        return <div className="p-8 text-center">Loading patient details...</div>;
    }

    if (!patientData) {
        return <div className="p-8 text-center text-red-500">Patient not found</div>;
    }

    return (
        <div className="space-y-6">
            <Link to="/doctor/patients" className="flex items-center text-gray-600 hover:text-gray-900 transition-colors">
                <ArrowLeft size={20} className="mr-2" /> Back to Patients
            </Link>

            {/* Patient Header */}
            <div className="card bg-white border-l-4 border-sage-500">
                <div className="flex justify-between items-start">
                    <div>
                        <h1 className="text-2xl font-bold text-gray-800">{patientData.user.firstName} {patientData.user.lastName}</h1>
                        <p className="text-gray-500">DOB: {new Date(patientData.user.dateOfBirth).toLocaleDateString()}</p>
                    </div>
                    {patientData.risk && (
                        <div className={`px-4 py-2 rounded-full text-sm font-bold ${patientData.risk.riskLevel === 'HIGH' ? 'bg-red-100 text-red-700' :
                                patientData.risk.riskLevel === 'MODERATE' ? 'bg-orange-100 text-orange-700' :
                                    'bg-green-100 text-green-700'
                            }`}>
                            Risk: {patientData.risk.riskLevel}
                        </div>
                    )}
                </div>
            </div>

            {/* AI Reports Section */}
            <div className="space-y-4">
                <h2 className="text-xl font-bold text-gray-800 flex items-center gap-2">
                    <Sparkles className="text-purple-500" /> AI Health Reports
                </h2>

                {reportsLoading ? (
                    <p className="text-gray-500">Loading reports...</p>
                ) : reports?.length === 0 ? (
                    <div className="bg-gray-50 border border-gray-200 rounded-lg p-8 text-center">
                        <p className="text-gray-500">No AI reports generated by this patient yet.</p>
                    </div>
                ) : (
                    <div className="grid gap-4">
                        {reports.map((report) => (
                            <div key={report.id} className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow">
                                <div className="flex justify-between items-center mb-4">
                                    <div className="flex items-center gap-2 text-sm text-gray-500">
                                        <FileText size={16} />
                                        {new Date(report.createdAt).toLocaleString()}
                                    </div>
                                    <div className="bg-purple-50 text-purple-700 px-2 py-1 rounded text-xs font-medium">
                                        Gemmi AI Report
                                    </div>
                                </div>
                                <div className="prose prose-sm max-w-none text-gray-700 whitespace-pre-wrap">
                                    {report.content}
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
};
